### ISSUE TITLE
Current TODO's

### ISSUE THREAD

**Issue by Xerbo** [Xerbo/aptdec#1]
This issue will serve as a marker for what's happening in development.

Soon:
 - [ ] Rewrite syncing
 - [ ] Make the windows build/building actually usable
 - [ ] Kill `pngio.c` with fire
 - [ ] Unit tests
 - [ ] Improve CPack building
 - [ ] GUI

Future:
 - [ ] Optimizations (multithreading, sample buffers, etc)
 - [ ] Speed comparison against other software

Done:
 - [x] CI
 - [x] Fixing the fact that `rt` produces different results to `tr`
 - [x] Windows support (cmake + mingw, may require ditching libsndfile)
 - [x] Crop noise out from image
 - [x] Use calibrated temperature for precipitation overlays & MCIR
 - [x] Rewrite false color
 - [x] Include utility scripts in this repo
 - [x] Raw image input, instead of having to do DSP each time.
 - [x] Image flipping, for southbound passes
 - [x] Better false color
 - [x] Fix temperature calibration
 - [x] Better commenting in files handling DSP
 - [x] Histogram equalisation
 - [x] Denoise filter
 - [x] Precipitation filter
 - [x] Real-time decoding
